//! Emit `BUILTIN_ENTRIES` from [`data/builtins.json`](../data/builtins.json) for the typechecker.

use serde_json::Value;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let json_path = Path::new(&manifest_dir).join("data/builtins.json");
    println!("cargo:rerun-if-changed={}", json_path.display());

    let raw = fs::read_to_string(&json_path).unwrap_or_else(|e| {
        panic!("read {}: {e}", json_path.display());
    });
    let arr: Vec<Value> = serde_json::from_str(&raw).expect("parse builtins.json");

    let mut out = String::from(
        "// @generated by build.rs\n\npub static BUILTIN_ENTRIES: &[super::BuiltinEntry] = &[\n",
    );
    for v in &arr {
        let dotted = v["dotted_name"].as_str().expect("dotted_name");
        let min_args = v["min_args"].as_u64().expect("min_args") as usize;
        let result = v["result"].as_str().expect("result");
        let ma = v["moving_average"].as_bool().expect("moving_average");
        let bn = v["binary_numeric"].as_bool().expect("binary_numeric");
        let un = v["unary_numeric"].as_bool().expect("unary_numeric");
        let usf = v["unary_string_to_float"]
            .as_bool()
            .expect("unary_string_to_float");
        let bb = v["bool_binary"].as_bool().expect("bool_binary");
        let sfa = v["series_from_args"].as_bool().expect("series_from_args");
        let nap = v["numeric_args_prefix"]
            .as_u64()
            .map(|n| n as usize)
            .unwrap_or(0);
        out.push_str(&format!(
            "    super::BuiltinEntry {{\n        dotted_name: {:?},\n        min_args: {},\n        result: super::BuiltinResultKind::{},\n        moving_average: {},\n        binary_numeric: {},\n        unary_numeric: {},\n        unary_string_to_float: {},\n        bool_binary: {},\n        series_from_args: {},\n        numeric_args_prefix: {},\n    }},\n",
            dotted, min_args, result, ma, bn, un, usf, bb, sfa, nap
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("builtin_entries_gen.rs");
    fs::write(&dest, out).expect("write builtin_entries_gen.rs");
}
